### ISSUE TITLE
Trigger release.

### ISSUE THREAD

**Issue by arthurfiorette** [micromatch/to-regex-range#19]
Since #17 got merged, this package wasn't updated on npm, so _we are not saving 440GB weekly yet_.

**Comment by arthurfiorette** [comment]
tagging @paulmillr since has was the one who approved #17.

**Comment by jonschlinkert** [comment]
I'm not doing this. I strongly disagree with this thinking, the reasoning behind it, and just the general idea of spending seconds thinking about this. 

More importantly, the premise is wrong. It doesn't save any bytes or make anything smaller. If it does, it's coincidental, not something you can know in advance. 

1. If two packages write the same code, you're increasing the size of the bundle
2. Tree shaking removes duplicate packages, but not duplicate inlined code
3. The fact that we had to go back and forth on the implementation of that function is more than enough justification for using a dependency. I've had to deal with many edge cases related to javascript numbers, and I really don't care if millions of developers think it's not necessary because they're clueless about the floating point bug and how javascript works.

**Comment by arthurfiorette** [comment]
You already merged the code. You could just `npm publish`...
