### ISSUE TITLE
Module stops working if the String.prototype has been extended

### ISSUE THREAD

**Issue by pitor** [micromatch/to-regex-range#6]
If I extend the String.prototype with a method the returned regexp string becomes invalid.

```js
const toRegexRange = require('to-regex-range');
String.prototype.equals = function(other) { return this == other; };
toRegexRange('15', '95');
```

returns:
`'1[5-9]function (other) { return this == other; }|[2-8]function (other) { return this == other; }[0-9]|9[0-5]function (other) { return this == other; }'`

It seems the problem is in the zip() function in the index.js

**Comment by doowb** [comment]
You shouldn't be modifying the prototype of built-in types. This can have unexpected effects as seen here.

If you need to modify the prototype, then define the property so it's non-enumerable:

```js
Object.defineProperty(String.prototype, 'equals', {
  value: function(other) {
    return this == other;
  }
});
```
`to-regex-range` is fine when you define `equals` that way.

Since this is the second issue (#3) we've gotten (and your's explains it better by providing the example), I think we should change the `for-in` in `zip` to a regular `for` loop. @pitor if you'd like to submit a PR for that change, I'll review it, otherwise I'll try to update it soon.
